
server:
  port: 8082
spring:
  application:
    name: 'transactions'
  datasource:
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/transactionsDb
    username: user
    password: password
    hikari:
      minimumIdle: 2
      maximumPoolSize: 5
      idleTimeout: 30000
      maxLifeTime: 200000
      connectionTimeout: 3000
      conectionTestQuery: select 1
      connectionInitSql: select 1
      poolName: Hikari
      schema: transactions
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      
      properties: 
        hibernate: 
          ddl-auto: none
          generate-ddl: false

  flyway:
    baseline-on-migrate: true
    schemas: transactions
    locations:
      - classpath:db/migration

  kafka:
    bootstrap-servers: http://localhost:29092
    consumer:
      group-id: consumer-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties: 
        spring.json.trusted.packages: com.projects.transactions.dto

hibernate:
  show_sql: true

logging:
  level:
    root: INFO
    com.projects.transaction: DEBUG
    org.hibernate: ERROR

kafka:
  topic:
    transaction: transactions
    consumer-type: json
